inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  SuggestExtensions: false

require:
  - rubocop-rails

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/controllers/api/v1/tin/validates_controller_spec.rb"